# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoveEvery_CA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ObjectMapper'
  pod 'Alamofire'

  target 'LoveEvery_CATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoveEvery_CAUITests' do
    # Pods for testing
  end

end
